site_name: Such Meme, Many Skill's Dumping Ground
theme: cinder
markdown_extensions:
  - admonition
  - pymdownx.arithmatex
nav:
    - Home: index.md
    - Guides:
        - 'Switch Theming Guide (external site)': 'https://nh-server.github.io/switch-guide/extras/theming/'
        - 'Switch Nand Restore Guide': 'guides/nandrestore.md'
        - 'Installing AutoRCM': 'guides/autorcm.md'
        - 'Switch Hackable Serial List': 'guides/switchserials.md'
        - 'Emummc manual Guide': 'guides/emunand.md'
        - 'Emummc manual linux Guide': 'guides/emunand_linux.md'
        - 'Switch Dump & Installing Guide': 'guides/switchdumpguide.md'
        
    - Apps:
        - 'Switch Theme Bat Script': 'apps/themebatscript.md'
        - 'Payload Launcher': 'apps/payload.md'
        - 'CubeAdventure - Game by me': 'apps/CubeAdventure.md'
    - Themes:
        - 'General Theme Sites': 'Themes/General_Theme_Sites.md'
        - 'My 3ds Themes': 'Themes/3ds_Themes.md'
        - 'My Switch Themes': 'Themes/Switch_Themes.md'
    - About: about.md
    
google_analytics:
    - UA-135654881-1
    - auto
    
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'